### ISSUE TITLE
Add @nuxt/babel-preset-app dependency 

### ISSUE THREAD

**Issue by timyourivh** [dword-design/nuxt-route-meta#104]
Without this dependency it will throw an error when trying to start 

<details>
  <summary>Show error</summary>
  
  ```
   ERROR  Cannot start nuxt:  Cannot find module '@nuxt/babel-preset-app'                                                                                                                           14:10:29  
Require stack:
- C:\wamp64\www\[project-name]\node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\files\configuration.js
- C:\wamp64\www\[project-name]\node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\files\index.js
- C:\wamp64\www\[project-name]\node_modules\nuxt-route-meta\node_modules\@babel\core\lib\index.js
- C:\wamp64\www\[project-name]\node_modules\nuxt-route-meta\dist\index.js
- C:\wamp64\www\[project-name]\node_modules\@nuxt\core-edge\dist\core.js

  Require stack:
  - node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\files\configuration.js
  - node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\files\index.js
  - node_modules\nuxt-route-meta\node_modules\@babel\core\lib\index.js
  - node_modules\nuxt-route-meta\dist\index.js
  - node_modules\@nuxt\core-edge\dist\core.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at resolve (node:internal/modules/cjs/helpers:108:19)
  at loadConfig (node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\files\configuration.js:172:5)
  at loadConfig.next (<anonymous>)
  at mergeExtendsChain (node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\config-chain.js:387:45)
  at mergeExtendsChain.next (<anonymous>)
  at node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\config-chain.js:373:20
  at Generator.next (<anonymous>)
  at buildRootChain (node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\config-chain.js:71:36)
  at buildRootChain.next (<anonymous>)
  at loadPrivatePartialConfig (node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\partial.js:103:62)
  at loadPrivatePartialConfig.next (<anonymous>)
  at loadFullConfig (node_modules\nuxt-route-meta\node_modules\@babel\core\lib\config\full.js:57:46)
  at loadFullConfig.next (<anonymous>)
  at Object.parse (node_modules\nuxt-route-meta\node_modules\@babel\core\lib\parse.js:25:45)
  at parse.next (<anonymous>)
  ```
</details>

As a workaround you can install this package manually and the error will be resolved.

My guess is this package got removed from `@babel/core` or `@babel/traverse` dependency's.

**Comment by dword-design** [comment]
@timyourivh When I install the latest version of Nuxt, `@nuxt/babel-preset-app` is installed. Still an issue?

**Comment by timyourivh** [comment]
Yes, this issue was not related to this package
